import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import HomeNavbar from "../ui/navbar/home-navbar/home-navbar";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { verifySession } from "@/lib/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  await verifySession()
  return (

      <main>
        <AppRouterCacheProvider>
          <nav>
            <HomeNavbar />
          </nav>
          {children}
        </AppRouterCacheProvider>
      </main>
  );
}
